---
namespace: sap

name: sap_operations

version: 1.2.3-galaxy

readme: README.md

authors:
  - Ondra Machacek <omachace@redhat.com>
  - Kirill Satarin (@kksat)

description: Ansible collection to handle day 2 operational SAP administration tasks.

license:
  - GPL-2.0-or-later

license_file: ''

tags:
  - linux
  - sap

dependencies: {}

repository: https://github.com/redhat-sap/rh_operations

documentation: https://github.com/redhat-sap/rh_operations

homepage: https://github.com/redhat-sap/rh_operations

issues: https://github.com/redhat-sap/rh_operations/issues

build_ignore:
  - roles/*/molecule
  - webdocs
  - docs
  - tests/output
  - .DS_Store
  - changelogs
  - changelogs-aap
  - changelogs-galaxy
  - __init__.py
  - plugins/__init__.py
  - plugins/doc_fragments/__init__.py
  - plugins/filter/__init__.py
  - plugins/module_utils/__init__.py
  - plugins/modules/__init__.py
  - plugins/test/__init__.py
  - galaxy-aap.yml
  - galaxy-galaxy.yml
